version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: compagnePub
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    entrypoint: ["/app/entrypoint.sh"]
    command: ["python", "app.py"]
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: compagnePub
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
