version: '3.8'

services:
  web:
    image: flask-backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db_c
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
