name: Docker Compose CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    env:
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: testdb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: sleep 10  # Ajuster si votre app est plus lente à démarrer

      - name: Test Flask backend endpoint
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5001/)
          if [ "$response" -ne 200 ]; then
            echo "Flask app test failed with HTTP status $response"
            exit 1
          else
            echo "Flask app is up and running!"
          fi

      - name: Shut down containers
        run: docker-compose down
