name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fix backend entrypoint script permissions
        run: |
          chmod +x backend/entrypoint.sh
          git update-index --chmod=+x backend/entrypoint.sh

      - name: Create .env file
        run: |
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_NAME=addcomp" >> .env
          echo "DB_PORT=5432" >> .env
          echo "FLASK_APP=app.py" >> .env
          echo "FLASK_ENV=development" >> .env

      - name: Start services with Docker Compose
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "⏳ Waiting for backend service..."
          timeout 60s bash -c 'until curl -s http://localhost:5000/api/health || curl -s http://localhost:5000/api/campaigns; do sleep 2; done'
          echo "⏳ Waiting for frontend service..."
          timeout 60s bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 2; done'

      - name: Check running containers
        run: docker ps -a

      - name: Test Backend API
        run: |
          echo "🔍 Testing Backend API"
          curl --fail http://localhost:5000/api/campaigns || (docker-compose logs backend && exit 1)

      - name: Test Frontend
        run: |
          echo "🔍 Testing Frontend"
          curl --fail http://localhost:3000 || (docker-compose logs frontend && exit 1)

      - name: Display logs if tests fail
        if: failure()
        run: docker-compose logs

      - name: Stop containers
        if: always()
        run: docker-compose down

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    # Changed from 'main' to 'master' to match the branch you're using
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fix backend entrypoint script permissions
        run: chmod +x backend/entrypoint.sh

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/addcomp-backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/addcomp-frontend:latest