test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install docker-compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Test with Docker Compose
      run: |
        docker-compose up -d
        sleep 30

        BACKEND_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
        echo "Backend status code: $BACKEND_STATUS"

        FRONTEND_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
        echo "Frontend status code: $FRONTEND_STATUS"

        if [ "$BACKEND_STATUS" -ne 200 ] && [ "$BACKEND_STATUS" -ne 404 ]; then
          echo "Backend service is not responding properly"
          docker-compose logs backend
          docker-compose down
          exit 1
        fi

        if [ "$FRONTEND_STATUS" -ne 200 ] && [ "$FRONTEND_STATUS" -ne 404 ]; then
          echo "Frontend service is not responding properly"
          docker-compose logs frontend
          docker-compose down
          exit 1
        fi

        echo "All services are running correctly"
        docker-compose down
