name: CI/CD Pipeline - Backend Only

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file for backend
        run: |
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_NAME=addcomp" >> .env
          echo "DB_PORT=5432" >> .env
          echo "FLASK_APP=app.py" >> .env
          echo "FLASK_ENV=development" >> .env

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start backend services
        run: |
          docker-compose -f docker-compose.backend.yml up -d --build
          echo "⏳ Attente du backend..."
          sleep 25

      - name: Check running containers
        run: docker ps -a

      - name: Test Backend API
        run: |
          echo "🔍 Test API Backend"
          curl --retry 5 --retry-connrefused --fail http://localhost:5000/api/campaigns || (docker-compose -f docker-compose.backend.yml logs && exit 1)

      - name: Display logs if tests fail
        if: failure()
        run: docker-compose -f docker-compose.backend.yml logs

      - name: Stop backend containers
        if: always()
        run: docker-compose -f docker-compose.backend.yml down

  deploy-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/addcomp-backend:latest
